pculture/unisubs

templates/teams/dashboard.html
Looks like the logic to turn this on got messed up with c5293efe284c.
I think the new code should work in all situations.
=> Fix team language select dialog (#1923)

apps/videos/views.py
=> Require a login for the create videos page (#1902)

media/src/js/unisubs.variations.js, settings.py, templates/_analytics.html, templates/_experiments.html, templates/base.html, templates/header.html, utils/context_processors.py
=> Gh 1969 refactor

templates/editor/tutorial.html
A few last minute wording tweaks.
=> Wording improvements in editor tutorial

templates/auth/login.html
=> Removed erroneous quoted in template

apps/api/tests/test_subtitles.py, apps/api/tests/test_videos.py, apps/api/urls.py, apps/api/views/__init__.py, apps/api/views/videos.py, utils/test_utils/__init__.py, utils/test_utils/api.py
Added a test utility to check the writable fields for a requset.
=> Implemented the new Video URL API endpoint

apps/subtitles/models.py, apps/subtitles/workflows.py
=> Add billing record if necessary when saving complete subtitles

deploy/requirements.txt
=> Updating django

media/src/js/embedder/embedder.js, media/src/js/popcorn/popcorn.amarasubtitle.js
=> Use frame event rather than timeupdate event to switch subtitles

templates/profiles/base.html
=> Fix profile language display

apps/auth/admin.py, apps/subtitles/views.py
for https://github.com/pculture/amara-enterprise/issues/123
=> Gh amara enterprise 123

deploy/requirements.txt
=> Increase required version of coverage

apps/api/middleware.py, settings.py
@bendk - I confirmed that these changes didn't break the existing api functionality / test cases for old or new.  Is there anything else that should be checked for this, or is that good enough to be able to merge.
=> Add CORS headers to api requests (#2160)

media/src/js/subtitle-editor/app.js, media/src/js/subtitle-editor/subtitles/controllers.js, templates/editor/dialogs.html
Fixes issues:
* #2169 : allow starting browsing subtitles with shortcut even if none selected
* #2170 : keys have different names on OSX, so help should refer to the proper name
* #2171 : fixes shortcut on mac osx by treating meta and alt interchangeably
=> Gh 2171shortcut fixes and improvements

apps/auth/admin.py
=> Fixed password fields on user edit form (#2168)

apps/api/views/activity.py
Added an optimization for the case when we get the team and language
param together.
=> Speedup activity queries

utils/applock.py, utils/test_utils/monkeypatch.py
Pretty simple change, but I figured it would be good to review it before merging to staging.
This is needed for amara-enterprise#146.
=> Added timeout paramater to applock

apps/videos/migrations/0169_auto__chg_field_videourl_url__del_unique_videourl_url_type.py, apps/videos/models.py
=> Gh 2248 alt

media/src/js/third-party/popcorn.js
See https://github.com/mozilla/popcorn-js/issues/458
=> Hack for youtube issue on Chrome

media/src/js/third-party/popcorn.js
Using a newer version of Popcorn, removing the patch for editor / Google Chrome compatibility issue.
=> Updated popcorn

apps/subtitles/forms.py, apps/subtitles/views.py, apps/teams/forms.py, apps/teams/permissions.py, apps/teams/workflows/old/subtitleworkflows.py, apps/teams/workflows/simple.py, apps/teams/workflows/startup.py, apps/teams/workflows/subtitleworkflows.py, apps/videos/views.py, templates/new-teams/base.html, templates/new-teams/settings-simple-workflow.html, templates/teams/dashboard.html
Adding new team type, with just 2 workflow settings - admission policy and video permission.
=> Simple workflow

apps/api/views/messages.py, apps/messages/forms.py, apps/messages/migrations/0003_auto__add_field_message_message_type.py, apps/messages/models.py, apps/messages/rpc.py, apps/messages/tasks.py, apps/messages/tests.py, apps/messages/views.py, media/css/v1.scss, media/js/unisubs.site.js, task_settings.py, templates/messages/inbox.html, templates/messages/sent.html
Current status of ted phase 3 messages. What's in:
* bulk treatment of messages
* better search within contacts
* cleanup policies and functions
* regular messages vs. notifications (+ old messages)
Known issue:
* Some notifications of comments do not have right type
Yet to be pushed:
* Better UI for displaying regular messages vs. notifications
=> Ted phase3 messages inbox

apps/videos/tests/test_video_types.py, apps/videos/types/dailymotion.py
Switch to using the requests library.
=> Fixed dailymotion video info fetching (#2353)

apps/subtitles/workflows.py, apps/teams/workflows/old/subtitleworkflows.py
This is for #pculture/amara-enterprise-353 - some transcripts failed to make it into the billing records, the change should fix this problem.
=> Try at fixing the billing records code

apps/subtitles/workflows.py
If someone a version gets set to private, make the Publish action
publish it.
=> Fix for subtitle visibility.

apps/api/tests/test_users.py, apps/api/views/users.py
=> Allow partners to create other partner accounts (#2362)

apps/api/views/subtitles.py
Importing dfxp subtitles with encoding specified.
=> Better fix for #2367

apps/videos/types/base.py
This is a tiny fix for an issue in logging when there is a problem downloading a video
=> Tiny fix for logging video download errors

apps/subtitles/views.py
Ref: (https://github.com/pculture/unisubs/issues/1832/)
=> Change the message when subtitles are locked for editing

apps/teams/workflows/old/subtitleworkflows.py, apps/teams/workflows/old/workflow.py
Fixing the bug with completed subtitles from non-task old-style teams not appearing in the billing records.
=> Gh amara enterprise 462

apps/messages/views.py
=> Escape user names in the message search

apps/messages/models.py
to block XSS in message body.
pculture/amara-enterprise#505
=> Escape HTML in message bodies

deploy/requirements.txt
This was already merged to production
=> upgrade pafy, resolves youtube download issue with at least one video

apps/subtitles/models.py, apps/subtitles/signals.py, apps/subtitles/workflows.py
A stab at fixing billing issues where billing records fail to get created.
=> Gh amara enterprise 574

apps/staff/views.py, apps/teams/new_views.py, apps/teams/views.py, apps/testhelpers/views.py, apps/videos/views.py, apps/widget/views.py, utils/decorators.py, views.py
This one redirects to the normal login page, not the admin one.
=> Use different staff_member_required wrapper

apps/teams/tasks.py, apps/videos/models.py
=> Fixed race condition in video creation and modification

middleware.py, settings.py
=> Set x-content-type-options haeder

apps/api/views/videos.py, apps/subtitles/workflows.py, apps/teams/workflows/subtitleworkflows.py
Adding permission checks for video URL manipulations.
=> Video url api fix

apps/api/views/subtitles.py, apps/api/views/teams.py
This one contains a fix for pculture/amara-enterprise#595 and also a fix for the TED crediting APi
=> Open teams and ted api tweak

templates/teams/_team_video_summary.html
=> Fixed template to display video title

apps/subtitles/forms.py, templates/editor/workflow-errors-review.html, templates/editor/workflow-errors-typing.html
Keep intact metadata from the previous version when uploading a new subtitle version.
=> Gh 986 refix

apps/api/views/videos.py
=> Set is_public in the video API endpoint

apps/api/tests/test_users.py, apps/api/views/users.py
Correcting permissions for viewing email address in the API browser.
=> Gh enterprise 648 revamp

apps/externalsites/google.py, apps/videos/types/youtube.py
=> get direct video files for youtube

templates/profiles/account.html
=> added new bullet point to youtube modal

templates/teams/_subnav_activity.html
Temporarily hid subnav link, awaiting new teams UI
=> Hide subnav link

media/src/css/subtitle-editor/subtitle-editor.scss, media/src/js/subtitle-editor/app.js, templates/editor/working-subtitles.html
Addresses Issue #1740
#1740
New in this pull request:
**-Clicking anywhere outside the menu will close the toolbox menu!**
Please let me know of any further usability issues with this button.
=> tool icon is toggable button AND toolbox menu has helper margin

apps/api/tests/test_users.py, apps/api/views/users.py, apps/auth/admin.py, apps/auth/migrations/0039_auto__add_field_customuser_allow_3rd_party_login.py, apps/auth/models.py, apps/externalsites/auth_backends.py
Enable staff and partners to create user accounts with Google OAuth token.
=> Gh enterprise 746

apps/api/tests/test_teams.py, apps/api/urls.py, apps/api/views/teams.py, apps/auth/models.py, apps/auth/signals.py, apps/auth/tests.py, apps/notifications/admin.py, apps/notifications/handlers.py, apps/notifications/migrations/0001_initial.py, apps/notifications/models.py, apps/notifications/signalhandlers.py, apps/notifications/tests.py, apps/subtitles/models.py, apps/subtitles/pipeline.py, apps/subtitles/signals.py, apps/subtitles/tests/test_signals.py, apps/teams/models.py, apps/teams/permissions.py, apps/teams/signals.py, apps/videos/models.py, docs/api-autogenerated.txt, docs/teams-callbacks.rst, settings.py, startup.py, utils/test_utils/monkeypatch.py, utils/test_utils/requests.py
New HTTP callback system for teams
=> Gh amara enterprise 729

media/src/css/subtitle-editor/subtitle-editor.scss
=> Fixed sizing of draggable areas on subtitles in the timeline.

apps/api/tests/test_videos.py, apps/api/views/videos.py, apps/subtitles/workflows.py
=> Updated permissions on the video API endpoint

media/src/js/subtitle-editor/app.js, media/src/js/subtitle-editor/subtitles/controllers.js, templates/editor/dialogs.html, templates/editor/working-subtitles.html
=> Revert "Gh 251"

apps/activity/management/commands/migrateactivity.py, apps/activity/models.py, apps/api/views/teams.py, apps/auth/models.py, apps/subtitles/pipeline.py, apps/testhelpers/views.py, apps/videos/management/commands/fix_blank_video_titles.py, apps/videos/models.py, startup.py, utils/compat/monkeypatch.py, utils/compat/xact.py, utils/management/commands/setup_test_data.py
This is what is used in newer versions of django and it handles nesting
better (see pculture/amara-enterprise#876).
Copied the xact() function, which apparently was the basis for atomic().
Added some code to put it in djangos transaction module.
=> Switch to using atomic() instead of commit_on_success()

deploy/requirements.txt
Fixed a problem with pulling data from YT.
=> Gh enterprise 1142

apps/notifications/admin.py, apps/notifications/handlers.py, apps/notifications/migrations/0003_auto__add_extrateamnotification.py, apps/notifications/models.py, apps/notifications/signalhandlers.py, apps/notifications/tests.py
Enabling callbacks in multi-team setup.
=> Gh unisubs 2739

apps/videos/management/commands/set_video_url_hash.py, apps/videos/migrations/0175_auto__chg_field_video_created__add_field_videourl_url_hash.py, apps/videos/models.py
Added the field and a command to populate it.  We should make sure that
they all get filled in before adding the uniqueness constraint.
=> Started work to using URL hashes for uninqueness checks.

apps/videos/types/htmlfive.py
Fixed an error with determining the duration of a video.
=> Improved avprobe parsing

apps/api/tests/test_teams.py, apps/api/tests/test_videos.py, apps/api/views/teams.py, apps/teams/models.py, apps/teams/tests/test_unpublish.py
Changing the default visibility setting for new teams.
=> Gh enterprise 1122

deploy/requirements.txt
=> Upgraded django

apps/videos/tests/test_template_tags.py, templates/future/paginator.html
Adding object count to videos and requests lists.
=> Gh enterprise 919

apps/api/tests/test_videos.py, apps/api/views/videos.py
Fixes the issue with video thumbnails submitted via API.
=> Gh amara enterprise 1208

media/src/js/embedder/embedder.js
=> Better fix for embedder controls

apps/teams/forms.py, apps/teams/oldforms.py, apps/teams/views.py
Making primary video language a mandatory field when adding a video to a team.
=> Gh enterprise 1244

apps/teams/new_views.py, templates/future/teams/management/videos-deselect-all.html, templates/future/teams/management/videos-select-all.html, templates/future/teams/management/videos.html
Fixes filters on Requests and Videos Management pages
=> Gh enterprise 1320

apps/auth/migrations/0042_alter_user_column_collation.py, utils/management/commands/setup_indexes.py
Make assignee pick tool in Edit Request modal case insensitive
=> Gh enterprise 1066

apps/videos/models.py
Suppress auto-creation of subtitle requests for completed languages
=> Gh enterprise 801

media/src/js/site/copytext.js, settings.py, templates/new-teams/settings-projects.html
pculture/amara-enterprise#1345
=> Added copy slug button to the projects settings page

apps/codefield/__init__.py, apps/teams/tests/test_forms.py, dev_settings_test.py, templates/profiles/dashboard.html, templates/profiles/view.html, utils/enum.py
=> Gh 1254 enterprise

apps/videos/views.py, media/amara/css/global/icons.scss, media/amara/js/ajax.js, templates/future/videos/subtitles.html, templates/future/videos/tabs/activity.html, templates/future/videos/video.html, utils/templatetags/query_string.py
=> Gh enterprise 1152

apps/teams/forms.py, apps/teams/tests/test_forms.py
Adding project filter to incoming requests tab and evaluations tab.
=> add support for source team projects on management page filters

apps/videos/forms.py
Fix for broken link on Add URL modal
=> move mark_safe outside of fmt call

apps/activity/models.py
Fixes displaying activity records for video URLs which contain %3D characters.
=> Gh enterprise 1479

apps/videos/views.py, media/amara/js/ajax.js, templates/future/videos/subtitles.html, templates/future/videos/tabs/sync-history.html
Update sync history tab via AJAX using a refresh button as well as when switching to tab (Resync button triggers a background task that can take a minute to complete).
=> Gh enterprise 1269

apps/messages/tasks.py, apps/teams/models.py
When an approve task is succesffuly completed, it should send notification to the reviewer AND to the original subtitler.
=> Gh unisubs 2843

README.markdown
Database should be configured first before starting the Amara Containers.
=> update quick start

apps/externalsites/admin.py, apps/externalsites/forms.py, apps/externalsites/tests/test_credit.py, apps/externalsites/tests/test_forms.py, apps/externalsites/tests/test_models.py, apps/externalsites/tests/test_syncing.py, templates/externalsites/new-team-settings-tab.html, templates/externalsites/team-settings-tab.html, utils/factories.py
Hides old Brightcove integration and adds short docs for the new one.
=> Gh enterprise 1566

media/amara/js/ajax.js
The idea is to parse the url each time we update the location and to re-inject the page into the new url. We also make sure the url changes before we do a pushstate.
=> Gh enterprise 1456

.travis.yml
=> travis yml config file

README.markdown
=> add travis-ci status image

media/amara/js/ajax.js
Only update the location if the form has changed.  In particular, don't
add a bunch of querystring values to the page when it's first opened.
Use querystring.parse() to get the page parameter.
=> Couple of cleanup pieces for the ajaxForm code

deploy/requirements.txt
=> add raven to requirements

settings.py
=> django raven integration

.travis.yml
=> add continuous integration

apps/videos/models.py, media/src/js/third-party/popcorn.js
Use vimeos's player.js api and repare vimeo player
=> Gh unisubs 3004

apps/teams/tests/test_team_videos.py, apps/videos/models.py
- When doing the duplicate public video check in update_team(), exclude
the video being moved.
- Refactored _check_prevent_duplicate_public_videos() to make it a bit
clearer.
- Added unittest for this
=> Fix for moving a video from the public area to a team (#1763)

apps/teams/workflows/subtitleworkflows.py
See pculture/amara-enterprise#1819
=> Allow superusers to view all team videos

media/src/js/subtitle-editor/video/directives.js
This makes saving subtitles enabled once you change a subtitle position
(#3270)
=> Register changing subtitle position as a change

apps/videos/behaviors.py
Fix for #3371 
Seems like the main functionality for the team workflow is working without new subtitles.html view involved, so I decided to not add tests for now.
=> Adding team slug to edit subtitle url via concatenation.

apps/ui/templatetags/forms.py, templates/future/teams/activity/stream.html, templates/future/teams/members/members.html
Made it not display the "(optional)" string.
Updated the activity/members pages to use it
Also pulling in some activity fixes from amara-enterprise
=> Updating render_filter_field
