pculture/unisubs

apps/videos/templatetags/paginator.py
templates/_paginator.html

Made the paginator tag work with the new object_list code.  Made the
paginate() function return the same keys as we use in object_list().
This pagination code is pretty messy and I would love to replace it.
Hopefully this will work in the meantime.

Fixed pagination code after refactor (#1960)

---

apps/teams/workflows/old/subtitleworkflows.py

Don't allow users to approve tasks if they aren't assigned and they
can't assign them to themselves.

Fix for #2067

---

apps/api/tests/test_activity.py
apps/api/views/activity.py

Renamed language_url -> language_uri to match the old field.  Fixed it
so that it pulls data from new_language, which is what we have used
since the DMR change. #2189

Fixed activity API language fields

---

apps/api/views/videos.py

I'm not sure why we're getting passed a list there, it seems like some
weird django-rest-factory thing.  In any case, just don't call
select_related() in that case and we can avoid the exception.

Fix new API code AttributeError (#2229)

---

apps/videos/types/dailymotion.py

Made it so DailymotionVideoType.matches_video_url() just checks the
form of the video URL, it doesn't actually try to make an API request.
This seems good in general to avoid requests and it also avoids the
exception in the API code.  The exception might happen in other
places, but I think that could be correct in those situations.

Simplify daily motion video URL matching (#2228)

---

docker-compose.yml

Entrypoints that aren't expressed as lists are broken in Docker 1.7.0,
which causes the whole setup procedure to fail when using that
version. Expressing the entrypoints as list should be harmless, while
working around the issue at least until 1.7.1 is released. Tested
with Docker 1.7.0 and docker-compose 1.3.1.
More about the underlying bug:
https://github.com/docker/compose/issues/1594
https://github.com/docker/docker/issues/14170

Workaround for entrypoints bug in Docker 1.7.0 (Docker issue #14170)

---

utils/templatetags/i18n_tags.py

Fixed the bug that resulted in '?' being displayed on team dashboard instead of 'French (Canada)'.
Tested locally on gh-2320.

Fixed language labels for non-task teams (#2320)

---

apps/api/views/subtitles.py

The point of this is to call video_changed_tasks() after the subtitles
are created.  video_changed_tasks() causes the video to be loaded then
saved from the DB, so we want it to happen after other changes happen.

Workaround for updating video titles (#2324)

---

media/src/css/site/lists.scss

If the image was a broken link, then some browsers display the alt
text.  Added CSS for this to make it only display 1 line of text.

Fixed alt text styling (pculture/amara-enterprise#403)

---

apps/api/views/subtitles.py

Enables to import DFXP files with the following in the first line:
<?xml version="1.0" encoding="UTF-8"?>

Fix for DFXP with an encoding specified (#2367)

---

media/src/css/site/split-view.scss

Long chunks of text in video description (such as long URLs) on collab detail page now do not spill over to the right side of the page.

Fixed text overflow on the sidebars (pculture/amara-enterprise#433)

---

apps/teams/new_views.py

This is for pculture/amara-enterprise#431
Display All Languages page for new team correctly when there are no videos/collabs in the team.

Fix for KeyError in the all languages page

---

apps/api/views/videos.py
apps/externalsites/google.py
apps/externalsites/tests/test_youtube_api.py
apps/videos/models.py
apps/videos/types/flv.py
apps/videos/types/htmlfive.py
apps/videos/types/mp3.py
apps/videos/types/vimeo.py
apps/videos/types/youtube.py
deploy/requirements.txt

* Public vimeo videos
* Fixes for long youtube videos, duration when no youtube API key
* Duration of mp4, mp3, flv files
* Make sure API does not override automatically set duration
* Get direct access to vimeo video files

Automatic duration settings of most video types

---

media/js/unisubs.site.js
templates/videos/diffing.html

2 fixes to the revisions / diffing pages:
1. Make the tip version on revisions page unchecked by default to simplify selection of any 2 versions for comparison.
2. Fix Revisions History button on the diffing page.

Revisions page

---

apps/videos/types/htmlfive.py

Works well on the local branch. Tested with the problem LL videos and randomly selected MP4, YT, and Vimeo videos.

Fixed incorrect calculation when stream set to duration 0

---

media/src/js/embedder/embedder.js

This fixes one of the first problems I encountered when testing this project locally. `embedder.js` was calling the API with a URL which discarded the subdomain and port; instead of hitting `http://amara.example.com:8000/api/videos/...`, it was hitting `http://example.com/api/videos`. This call was blocked since this was a cross-origin HTTP request, so pages like `/en/videos/...` would fail to load.
This seems like it was an isolated bug. This change switches it to simply use a relative path for the request, which seems to work quite nicely.

Switching embedder to user relative path for Video API

---

apps/teams/models.py
apps/teams/templatetags/teams_tags.py
templates/new-teams/videos.html

Don't fetch the teamvideo for each video.  We don't even use the
variable.
Cached counting videos per-project.  Some on-demand teams have dozens of
projects and running a query for each is quite slow.

Speed up the team videos page

---

media/src/css/subtitle-editor/subtitle-editor.scss
templates/editor/working-subtitles.html

Addresses Issue #1740
https://github.com/pculture/unisubs/issues/1740
An empty, invisible div was added to extend the hover area of the editor hover menu.
It acts as an extra margin of 45px to the left of the menu,
eliminating the gap between the icon and the hover menu,
where it is very easy to fall out of the hover area and lose the menu.
This margin runs the full lenght of the editor hover menu,
but can obviously be shortened to match the lenght of the tool icon
if the current area provides too much hover space.

Added extra margin to editor hover menu

---

apps/api/views/subtitles.py
apps/subtitles/views.py
apps/subtitles/workflows.py
apps/teams/tests/test_notes.py
apps/teams/workflows/old/subtitleworkflows.py
apps/teams/workflows/subtitleworkflows.py
media/src/js/subtitle-editor/notes.js
templates/editor/notes.html

Include the user when calling SubtitleWorkflow.get_editor_notes().
Allow the method to return None to disable notes.
This is needed for the evaluation teams feature.  For that there are
cases where we want to allow users to edit the subtitles, but not see
the notes.

Added some extra permissions checking for notes

---

media/src/js/subtitle-editor/subtitles/directives.js

Fixes #2637.
References for using $timeout to update layout based on DOM updates (since this doesn't seem to be directly documented by angularjs):
- https://github.com/angular/angular.js/issues/734
- http://stackoverflow.com/questions/19183049/how-to-call-a-function-when-angular-is-done-updating-the-layout-because-of-data
- http://stackoverflow.com/questions/16066239/defer-angularjs-watch-execution-after-digest-raising-dom-event
- http://stackoverflow.com/questions/29093229/how-to-call-function-when-angular-watch-cycle-or-digest-cycle-is-completed
- http://tech.endeepak.com/blog/2014/05/03/waiting-for-angularjs-digest-cycle/

Ensured info tray is repositioned after subtitle text & DOM updates

---

apps/subtitles/permissions.py

Currently, one of the test breaks because trying to get or set subtitles with no format specified fails saing permission is denied, while it should default to `dfxp`. This commit resolves this issue.

Fix permission for case when no subtitle type is specified

---

media/src/js/subtitle-editor/app.js

The issue is that we push subtitles via the API with a "save-draft" action name. But this action is not valid after subtitles are published.
In branch gh-2710, this was fixed by not setting the action name, it should be set automatically.

Fix for action name when uploading subtitles from editor

---

apps/teams/models.py

This fixes an error when adding new team videos: metadata are updated twice in two different thread, making them wrong most of the time

Fixed metada from youtube when adding team video

---

media/src/js/subtitle-editor/timeline/directives.js

Fixes the problem of timeline messed up in the latest FF.

Workaround for Firefox issue with CSS properties of hidden elements

---

apps/teams/forms.py
apps/teams/views.py
templates/teams/videos-list.html

Made it so we call prepare_value() which should do the right thing
regardless of if we use ids, slugs, or whatever for project values.
Fixed prepare_value() so that it works with our hack to use slugs for
now.

Fix for project filter initial values

---

apps/externalsites/models.py
apps/videos/oldviews.py

I'm not sure how this happens, but we have instances of an multiple
SyncedSubtitleVersion objects in the database for a single
video_url/language tuple.  It seems that this happens when the account
gets deleted, but we don't delete the related SyncedSubtitleVersion
object.  Maybe this has to do with old code, not sure.
In any case, I made it so we figure out which SyncedSubtitleVersion is
the correct one for the current sync account and we use that one.

Prevent exception with old syncedsubtitleversions (#2770)

---

apps/activity/models.py

That followed the issue we had, probably from people using the legacy instance, with language codes not having properly mapped.

Makes activity records display more robust to erroneous language codes

---

apps/teams/admin.py

Filtering teams is overridden to only return teams that are not marked as deleted. The function we have to search for team members breaks in that case.

Do not break for members of deleted teams

---

apps/api/views/subtitles.py

Noticed a few spelling/grammar errors in the documentation and decided to fix them.  Not the most important of changes, I'm sure, so feel free to ignore if this is unwanted.

Minor spelling/grammar fixes in the documentation

---

apps/externalsites/google.py

API call fails if trying to submit a title longer than 100 characters.

Limit title length when pushing to youtube

---

apps/externalsites/models.py
apps/externalsites/tasks.py
apps/videos/models.py
apps/videos/tests/test_video_types.py
apps/videos/types/base.py
apps/videos/types/dailymotion.py
apps/videos/types/flv.py
apps/videos/types/googledrive.py
apps/videos/types/htmlfive.py
apps/videos/types/mp3.py
apps/videos/types/ustream.py
apps/videos/types/video_google.py
apps/videos/types/vimeo.py
apps/videos/types/wistia.py
apps/videos/types/youtube.py

This implements what is said in the ticket (only synchronously check for up to 5 linked accounts for metadata in yotube video), but also cleans up the way we add owner_username, to limit API calls and also use authenticated API calls to get the value for private youtube videos.

Gh enterprise 1612

---

apps/teams/forms.py

teams setting page doesn't include the future ui assets which the new file field widgets use, so for now using the old field widgets on this page

use old file inputs for settings page

---

apps/api/views/videos.py
apps/teams/forms.py
apps/videos/management/commands/encode_urls.py
apps/videos/models.py
apps/videos/tests/test_models.py
apps/videos/types/base.py
apps/videos/types/flv.py
apps/videos/types/htmlfive.py
apps/videos/types/mp3.py
utils/url_escape.py

* We now use percent-encoded URLs, generated from IRIs when URLs are submitted
* A management command converts existing IRIs to percent-encoded URLs
* Fixed an issue when adding multiple URLs
* Fixed an issue with errors messages in API when a URL with unicode characters had an issue
* Properly retrieves video duration of all videos (was failing for IRIs with unicode characters
* Fixed an issue with the form when adding multiple URLs
* Made max length of video urls consistent across API and UI

Various fixes and improvements for Video URLs
